name: stock-predictor
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - streamlit
      - numpy==2.4.4
      - pandas==3.0.2
      - matplotlib
      - scikit-learn==1.8.0
      - tensorflow==2.21.0
      - keras==3.14.0
      - joblib==1.5.3
      - seaborn
      - yfinance
